apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent-operator-chart
  namespace: argocd
spec:
  destination:
    namespace: grafana-agent-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-agent-operator
    targetRevision: "0.2.15"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
